# Generated by Django 3.1.3 on 2020-12-31 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsmaGOwebapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('curso', models.CharField(max_length=255)),
                ('colegio', models.CharField(max_length=255)),
                ('sintomas_diurnos', models.CharField(max_length=255)),
                ('medicacion', models.CharField(max_length=255)),
                ('sintomas_nocturnos', models.CharField(max_length=255)),
                ('ataques', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
