# Generated by Django 3.1.3 on 2020-12-27 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AsmaGOwebapp', '0002_auto_20201223_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='resistencia',
        ),
        migrations.RemoveField(
            model_name='students',
            name='velocidad',
        ),
    ]
