# Generated by Django 3.1.3 on 2020-12-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsmaGOwebapp', '0003_auto_20201227_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='resistencia',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='students',
            name='velocidad',
            field=models.CharField(default='', max_length=255),
        ),
    ]
