# Generated by Django 3.1.3 on 2020-12-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsmaGOwebapp', '0004_auto_20201227_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='resistencia',
            new_name='ataques',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='velocidad',
            new_name='medicacion',
        ),
        migrations.AddField(
            model_name='students',
            name='sintomas_diurnos',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='students',
            name='sintomas_nocturnos',
            field=models.CharField(default='', max_length=255),
        ),
    ]
