# Generated by Django 3.1.3 on 2020-12-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsmaGOwebapp', '0005_auto_20201227_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='sintomas_diurnos',
            field=models.CharField(default='', help_text='aaaaaaaa', max_length=255),
        ),
    ]
