# Generated by Django 3.1.3 on 2020-12-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsmaGOwebapp', '0006_auto_20201227_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='ataques',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='medicacion',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='sintomas_diurnos',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='sintomas_nocturnos',
            field=models.IntegerField(max_length=10),
        ),
    ]
