# Generated by Django 3.1.3 on 2020-12-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsmaGOwebapp', '0008_auto_20201227_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='ataques',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='students',
            name='medicacion',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='students',
            name='sintomas_diurnos',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='students',
            name='sintomas_nocturnos',
            field=models.CharField(default='', max_length=255),
        ),
    ]
