# Generated by Django 3.1.3 on 2020-12-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsmaGOwebapp', '0011_auto_20201228_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
