# Generated by Django 3.1.3 on 2020-12-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsmaGOwebapp', '0012_auto_20201228_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='dedos',
            field=models.CharField(default='', max_length=255),
        ),
    ]
