# Generated by Django 3.1.3 on 2020-12-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsmaGOwebapp', '0016_auto_20201229_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='ataques',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='medicacion',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='sintomas_diurnos',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='sintomas_nocturnos',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
