# Generated by Django 3.1.3 on 2020-12-29 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AsmaGOwebapp', '0018_auto_20201229_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='dedos',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='gender',
        ),
    ]
