# Generated by Django 3.1.3 on 2020-12-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsmaGOwebapp', '0019_auto_20201229_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='dedos',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='gender',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
