# Generated by Django 3.1.3 on 2020-12-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsmaGOwebapp', '0022_auto_20201229_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='email',
        ),
        migrations.AddField(
            model_name='studentdata',
            name='colegio',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='curso',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
