# Generated by Django 3.1.3 on 2020-12-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsmaGOwebapp', '0023_auto_20201229_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='colegio',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='curso',
            field=models.CharField(max_length=255),
        ),
    ]
